apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: e2e-nodejs
    appstudio.openshift.io/component: nodejs-component
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: nodejs-component
  namespace: e2e-demo-lazt
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_redhat-appstudio-qe_simple-nodejs-app
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/redhat-appstudio-qe/simple-nodejs-app
