apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-component
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-component
  namespace: e2e-demo-lazt
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs-component
    weight: 100
status: {}
