apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-component
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-component
  namespace: e2e-demo-lazt
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nodejs-component
status:
  loadBalancer: {}
